<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face.proto

namespace App\Grpc\Face_recog_package;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 1:1验证请求
 *
 * Generated from protobuf message <code>face_recog_package.FaceServ1VS1Request</code>
 */
class FaceServ1VS1Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string message = 1;</code>
     */
    private $message = '';
    /**
     * Generated from protobuf field <code>string image1 = 2;</code>
     */
    private $image1 = '';
    /**
     * Generated from protobuf field <code>string image2 = 3;</code>
     */
    private $image2 = '';
    /**
     *  用户ID
     *
     * Generated from protobuf field <code>string userID = 4;</code>
     */
    private $userID = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message
     *     @type string $image1
     *     @type string $image2
     *     @type string $userID
     *            用户ID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Face::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string image1 = 2;</code>
     * @return string
     */
    public function getImage1()
    {
        return $this->image1;
    }

    /**
     * Generated from protobuf field <code>string image1 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setImage1($var)
    {
        GPBUtil::checkString($var, True);
        $this->image1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string image2 = 3;</code>
     * @return string
     */
    public function getImage2()
    {
        return $this->image2;
    }

    /**
     * Generated from protobuf field <code>string image2 = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setImage2($var)
    {
        GPBUtil::checkString($var, True);
        $this->image2 = $var;

        return $this;
    }

    /**
     *  用户ID
     *
     * Generated from protobuf field <code>string userID = 4;</code>
     * @return string
     */
    public function getUserID()
    {
        return $this->userID;
    }

    /**
     *  用户ID
     *
     * Generated from protobuf field <code>string userID = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUserID($var)
    {
        GPBUtil::checkString($var, True);
        $this->userID = $var;

        return $this;
    }

}

