<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face.proto

namespace App\Grpc\Face_recog_package;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 请求信息数据定义
 *
 * Generated from protobuf message <code>face_recog_package.FaceServRequestMsg</code>
 */
class FaceServRequestMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServMsgType type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServDetectRequest req_det = 2;</code>
     */
    private $req_det = null;
    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServ1VS1Request req_1vs1 = 3;</code>
     */
    private $req_1vs1 = null;
    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServRegisterRequest req_register = 4;</code>
     */
    private $req_register = null;
    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServ1VSNRequest req_1vsN = 5;</code>
     */
    private $req_1vsN = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type \Face_recog_package\FaceServDetectRequest $req_det
     *     @type \Face_recog_package\FaceServ1VS1Request $req_1vs1
     *     @type \Face_recog_package\FaceServRegisterRequest $req_register
     *     @type \Face_recog_package\FaceServ1VSNRequest $req_1vsN
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Face::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServMsgType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServMsgType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Face_recog_package\FaceServMsgType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServDetectRequest req_det = 2;</code>
     * @return \Face_recog_package\FaceServDetectRequest
     */
    public function getReqDet()
    {
        return $this->req_det;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServDetectRequest req_det = 2;</code>
     * @param \Face_recog_package\FaceServDetectRequest $var
     * @return $this
     */
    public function setReqDet($var)
    {
        GPBUtil::checkMessage($var, \Face_recog_package\FaceServDetectRequest::class);
        $this->req_det = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServ1VS1Request req_1vs1 = 3;</code>
     * @return \Face_recog_package\FaceServ1VS1Request
     */
    public function getReq1Vs1()
    {
        return $this->req_1vs1;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServ1VS1Request req_1vs1 = 3;</code>
     * @param \Face_recog_package\FaceServ1VS1Request $var
     * @return $this
     */
    public function setReq1Vs1($var)
    {
        GPBUtil::checkMessage($var, \Face_recog_package\FaceServ1VS1Request::class);
        $this->req_1vs1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServRegisterRequest req_register = 4;</code>
     * @return \Face_recog_package\FaceServRegisterRequest
     */
    public function getReqRegister()
    {
        return $this->req_register;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServRegisterRequest req_register = 4;</code>
     * @param \Face_recog_package\FaceServRegisterRequest $var
     * @return $this
     */
    public function setReqRegister($var)
    {
        GPBUtil::checkMessage($var, \Face_recog_package\FaceServRegisterRequest::class);
        $this->req_register = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServ1VSNRequest req_1vsN = 5;</code>
     * @return \Face_recog_package\FaceServ1VSNRequest
     */
    public function getReq1VsN()
    {
        return $this->req_1vsN;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServ1VSNRequest req_1vsN = 5;</code>
     * @param \Face_recog_package\FaceServ1VSNRequest $var
     * @return $this
     */
    public function setReq1VsN($var)
    {
        GPBUtil::checkMessage($var, \Face_recog_package\FaceServ1VSNRequest::class);
        $this->req_1vsN = $var;

        return $this;
    }

}

