<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face.proto

namespace App\Grpc\Face_recog_package;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 注册接口结果
 *
 * Generated from protobuf message <code>face_recog_package.FaceServRegisterResult</code>
 */
class FaceServRegisterResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string message = 1;</code>
     */
    private $message = '';
    /**
     * 返回码， 成功为0,其他为非0
     *
     * Generated from protobuf field <code>int32 ret_code = 2;</code>
     */
    private $ret_code = 0;
    /**
     *  用户ID
     *
     * Generated from protobuf field <code>string userID = 3;</code>
     */
    private $userID = '';
    /**
     *  用户的关注组，比如一个用户有多个关注组用于人脸搜索，默认组名字是default
     *
     * Generated from protobuf field <code>string groupID = 4;</code>
     */
    private $groupID = '';
    /**
     *  人脸唯一ID
     *
     * Generated from protobuf field <code>string faceID = 5;</code>
     */
    private $faceID = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message
     *     @type int $ret_code
     *           返回码， 成功为0,其他为非0
     *     @type string $userID
     *            用户ID
     *     @type string $groupID
     *            用户的关注组，比如一个用户有多个关注组用于人脸搜索，默认组名字是default
     *     @type string $faceID
     *            人脸唯一ID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Face::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * 返回码， 成功为0,其他为非0
     *
     * Generated from protobuf field <code>int32 ret_code = 2;</code>
     * @return int
     */
    public function getRetCode()
    {
        return $this->ret_code;
    }

    /**
     * 返回码， 成功为0,其他为非0
     *
     * Generated from protobuf field <code>int32 ret_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRetCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->ret_code = $var;

        return $this;
    }

    /**
     *  用户ID
     *
     * Generated from protobuf field <code>string userID = 3;</code>
     * @return string
     */
    public function getUserID()
    {
        return $this->userID;
    }

    /**
     *  用户ID
     *
     * Generated from protobuf field <code>string userID = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserID($var)
    {
        GPBUtil::checkString($var, True);
        $this->userID = $var;

        return $this;
    }

    /**
     *  用户的关注组，比如一个用户有多个关注组用于人脸搜索，默认组名字是default
     *
     * Generated from protobuf field <code>string groupID = 4;</code>
     * @return string
     */
    public function getGroupID()
    {
        return $this->groupID;
    }

    /**
     *  用户的关注组，比如一个用户有多个关注组用于人脸搜索，默认组名字是default
     *
     * Generated from protobuf field <code>string groupID = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupID($var)
    {
        GPBUtil::checkString($var, True);
        $this->groupID = $var;

        return $this;
    }

    /**
     *  人脸唯一ID
     *
     * Generated from protobuf field <code>string faceID = 5;</code>
     * @return string
     */
    public function getFaceID()
    {
        return $this->faceID;
    }

    /**
     *  人脸唯一ID
     *
     * Generated from protobuf field <code>string faceID = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFaceID($var)
    {
        GPBUtil::checkString($var, True);
        $this->faceID = $var;

        return $this;
    }

}

