<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face.proto

namespace App\Grpc\Face_recog_package;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 响应信息数据定义
 *
 * Generated from protobuf message <code>face_recog_package.FaceServReplyMsg</code>
 */
class FaceServReplyMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServMsgType type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServDetectResult ret_det = 2;</code>
     */
    private $ret_det = null;
    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServ1VS1Result ret_1vs1 = 3;</code>
     */
    private $ret_1vs1 = null;
    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServRegisterResult ret_register = 4;</code>
     */
    private $ret_register = null;
    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServ1VSNResult ret_1vsN = 5;</code>
     */
    private $ret_1vsN = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type \Face_recog_package\FaceServDetectResult $ret_det
     *     @type \Face_recog_package\FaceServ1VS1Result $ret_1vs1
     *     @type \Face_recog_package\FaceServRegisterResult $ret_register
     *     @type \Face_recog_package\FaceServ1VSNResult $ret_1vsN
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Face::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServMsgType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServMsgType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Face_recog_package\FaceServMsgType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServDetectResult ret_det = 2;</code>
     * @return \Face_recog_package\FaceServDetectResult
     */
    public function getRetDet()
    {
        return $this->ret_det;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServDetectResult ret_det = 2;</code>
     * @param \Face_recog_package\FaceServDetectResult $var
     * @return $this
     */
    public function setRetDet($var)
    {
        GPBUtil::checkMessage($var, \Face_recog_package\FaceServDetectResult::class);
        $this->ret_det = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServ1VS1Result ret_1vs1 = 3;</code>
     * @return \Face_recog_package\FaceServ1VS1Result
     */
    public function getRet1Vs1()
    {
        return $this->ret_1vs1;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServ1VS1Result ret_1vs1 = 3;</code>
     * @param \Face_recog_package\FaceServ1VS1Result $var
     * @return $this
     */
    public function setRet1Vs1($var)
    {
        GPBUtil::checkMessage($var, \Face_recog_package\FaceServ1VS1Result::class);
        $this->ret_1vs1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServRegisterResult ret_register = 4;</code>
     * @return \Face_recog_package\FaceServRegisterResult
     */
    public function getRetRegister()
    {
        return $this->ret_register;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServRegisterResult ret_register = 4;</code>
     * @param \Face_recog_package\FaceServRegisterResult $var
     * @return $this
     */
    public function setRetRegister($var)
    {
        GPBUtil::checkMessage($var, \Face_recog_package\FaceServRegisterResult::class);
        $this->ret_register = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServ1VSNResult ret_1vsN = 5;</code>
     * @return \Face_recog_package\FaceServ1VSNResult
     */
    public function getRet1VsN()
    {
        return $this->ret_1vsN;
    }

    /**
     * Generated from protobuf field <code>.face_recog_package.FaceServ1VSNResult ret_1vsN = 5;</code>
     * @param \Face_recog_package\FaceServ1VSNResult $var
     * @return $this
     */
    public function setRet1VsN($var)
    {
        GPBUtil::checkMessage($var, \Face_recog_package\FaceServ1VSNResult::class);
        $this->ret_1vsN = $var;

        return $this;
    }

}

